---
resources:
  - name: gonfig 
    type: git
    source:
      uri: https://github.com/dgruber/gonfig.git
      branch: demo

  - name: push
    type: cf
    source:
      api: {{pcf_api}}
      username: {{pcf_user}}
      password: {{pcf_password}}  
      organization: {{pcf_org}}
      space: {{pcf_space}}  
      skip_cert_check: true

jobs:
  - name: building
    plan:
      - get: gonfig
        trigger: true
      - task: build
        file: gonfig/ci/tasks/build_gonfig.yml

  - name: testing
    plan:
      - get: gonfig
        passed: [building]
        trigger: true
      - task: test
        file: gonfig/ci/tasks/test_gonfig.yml

  - name: example
    plan:
      - get: gonfig
        passed: [testing]
        trigger: true
      - task: example
        file: gonfig/ci/tasks/example.yml
      - put: push
        params:
          manifest: gonfig/example/manifest.yml
          path: gonfig/example
          environment_variables:
            key: value
