---
resources:
  - name: gonfig 
    type: git
    source:
      uri: https://github.com/dgruber/gonfig.git
      branch: master

jobs:
  - name: building
    plan:
      - get: gonfig
        trigger: true
      - task: build
        file: gonfig/ci/build_gonfig.yml
        on_success:
          task: test
          file: gonfig/ci/test_gonfig.yml
