---
resources:
  - name: gonfig 
    type: git
    source:
      uri: https://github.com/dgruber/gonfig.git
      branch: master

jobs:
  - name: building
    plan:
      - get: gonfig
        trigger: true
      - task: build
        file: gonfig/ci/tasks/build_gonfig.yml

  - name: testing
    plan:
      - get: gonfig
        passed: [building]
        trigger: true
      - task: test
        file: gonfig/ci/tasks/test_gonfig.yml

  - name: example
    plan:
      - get: gonfig
        passed: [testing]
        trigger: true
      - task: example
        file: gonfig/ci/tasks/example.yml
